"""assemble_changelog.py — build CHANGELOG.md from per-slice changelog.json records (v2, NEW).

Single-skill helper for `/product-doc`. The DETERMINISTIC half of doc generation: `/commit-slice`
already writes one `changelog.json` per shipped slice into `<vault>/slices/archive/slice-NNN-<name>/`
(schema `aisdlc/changelog@1`). This script aggregates them into a Keep-a-Changelog-style `CHANGELOG.md`
— no model, no hallucination, just the audited per-slice records the pipeline already produced.

Grouping: conventional-commit `type` -> Keep-a-Changelog section (feat->Added, fix->Fixed, the rest->Changed).
Entries are sorted newest-first by slice number. Each line cites the slice id + any ADRs (the provenance anchor).

Output:
  - default: print the CHANGELOG markdown to STDOUT (utf-8-reconfigured, so em-dashes don't crash cp1252).
  - `--out PATH`: write the markdown to PATH (utf-8) and print PATH.

Exit 0 success (an empty archive yields a valid minimal CHANGELOG) · 2 usage error (bad --vault).
"""
from __future__ import annotations

import argparse
import glob
import json
import os
import pathlib
import re
import sys
from pathlib import Path

# --- single-skill import bootstrap (cannot use `python -m` for a bundled script) ---
_REPO = pathlib.Path(__file__).resolve().parents[3]  # skills/<name>/scripts/X.py -> <plugin>
if str(_REPO) not in sys.path:
    sys.path.insert(0, str(_REPO))

from scripts.lib import _stdout  # noqa: E402

# conventional-commit type -> Keep-a-Changelog section. Unknown types fall to "Changed".
_SECTION = {
    "feat": "Added",
    "fix": "Fixed",
    "perf": "Changed",
    "refactor": "Changed",
    "build": "Changed",
    "chore": "Changed",
    "docs": "Changed",
    "style": "Changed",
    "test": "Changed",
    "revert": "Changed",
}
_SECTION_ORDER = ["Added", "Changed", "Fixed"]
_SLICE_NUM = re.compile(r"slice-(\d+)")


def _slice_num(rec: dict, folder: str) -> int:
    """Sort key: slice number from the record's `slice` field, else the folder name."""
    m = _SLICE_NUM.search(str(rec.get("slice") or folder))
    return int(m.group(1)) if m else -1


def _load_changelogs(vault: str) -> list[tuple[int, dict]]:
    out: list[tuple[int, dict]] = []
    for f in glob.glob(os.path.join(vault, "slices", "archive", "*", "changelog.json")):
        try:
            with open(f, encoding="utf-8") as fh:
                rec = json.load(fh)
        except (OSError, ValueError):
            continue  # skip unreadable / malformed — never abort the whole changelog on one bad file
        out.append((_slice_num(rec, os.path.basename(os.path.dirname(f))), rec))
    out.sort(key=lambda t: t[0], reverse=True)  # newest slice first
    return out


def _entry_line(rec: dict) -> str:
    scope = str(rec.get("scope") or "").strip()
    # prefer the human one-liner `intent`; fall back to `subject` with any conventional prefix stripped
    desc = str(rec.get("intent") or "").strip()
    if not desc:
        subj = str(rec.get("subject") or "").strip()
        desc = re.sub(r"^\w+(\([^)]*\))?:\s*", "", subj)  # drop "feat(scope): " prefix if present
    sl = str(rec.get("slice") or "").strip()
    adrs = rec.get("adrs") or []
    adr_str = f" [{', '.join(adrs)}]" if adrs else ""
    prefix = f"**{scope}:** " if scope else ""
    cite = f" ({sl})" if sl else ""
    return f"- {prefix}{desc}{cite}{adr_str}".rstrip()


def _render(records: list[tuple[int, dict]]) -> str:
    lines = [
        "# Changelog",
        "",
        "All notable changes to this project, generated by `/product-doc` from the per-slice "
        "`changelog.json` records `/commit-slice` writes. Do not hand-edit — regenerate.",
        "",
        "## [Unreleased]",
        "",
    ]
    if not records:
        lines += ["_No shipped slices yet._", ""]
        return "\n".join(lines)

    buckets: dict[str, list[str]] = {s: [] for s in _SECTION_ORDER}
    for _, rec in records:
        section = _SECTION.get(str(rec.get("type") or "").strip().lower(), "Changed")
        buckets.setdefault(section, []).append(_entry_line(rec))

    for section in _SECTION_ORDER:
        if buckets.get(section):
            lines.append(f"### {section}")
            lines.append("")
            lines += buckets[section]
            lines.append("")
    return "\n".join(lines)


def _build_arg_parser() -> argparse.ArgumentParser:
    p = argparse.ArgumentParser(
        prog="assemble_changelog",
        description="Aggregate per-slice changelog.json records into CHANGELOG.md (/product-doc).",
    )
    p.add_argument("--vault", required=True, help="vault root (contains slices/archive/*/changelog.json)")
    p.add_argument("--out", default=None, help="write CHANGELOG markdown to this file and print the path "
                                               "(default: print the markdown to stdout)")
    return p


def main(argv: list[str] | None = None) -> int:
    _stdout.reconfigure_stdout_utf8()
    args = _build_arg_parser().parse_args(argv)

    vault = args.vault.strip()
    if not vault:
        sys.stderr.write("assemble_changelog: --vault is required\n")
        return 2

    md = _render(_load_changelogs(vault))
    if args.out:
        try:
            Path(args.out).write_text(md + "\n", encoding="utf-8", newline="\n")
        except OSError as exc:
            sys.stderr.write(f"assemble_changelog: cannot write --out {args.out}: {exc}\n")
            return 2
        print(args.out)
    else:
        print(md)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
